# Generated by Django 3.2.5 on 2021-09-18 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210914_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
